
app.version: 1.0.0

security.require-ssl: true

spring:
    datasource:
#        url: jdbc:mysql://bts-rds-mysql.crgmhghbkuyc.us-east-1.rds.amazonaws.com/bts?characterEncoding=utf8
#        username: admin
#        password: mypassword

        url: jdbc:mysql://localhost:3306/bts?characterEncoding=utf8
        username: root
        password: root

    jpa: 
        hibernate:
            hbm2ddl.auto: update
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            show-sql: true



server:
    max-http-header-size: 9192

    port: 9443
    ssl:
        key-store-type: PKCS12
        key-store: classpath:keystore/broadviewsoft.p12
        key-store-password: changeit
        key-alias: broadviewsoft
